sudo: false
language: node_js

node_js: "12"

cache:
  directories:
    - node_modules

env:
  global:
    - COVERALLS_PARALLEL=true

script: 
  - npm run test

after_script:
  - npm run test | coveralls

notifications:
  webhooks: https://coveralls.io/webhook